// Generated by OrchestKit Claude Plugin
// Created: 2026-08-25

import { describe, expect, it } from 'vitest';
import { searchComponentCandidates } from '../../src/registry-explorer/core/discovery';
import { buildRegistryProfile } from '../../src/registry-explorer/core/registryProfile';
import { buildRelatedComponents } from '../../src/registry-explorer/core/relatedComponents';
import { resolveRegistryItemDetailFromSummary } from '../../src/registry-explorer/core/registryItemDetail';
import { renderItemDetailView } from '../../src/registry-explorer/ui/itemDetailView';
import type { Registry } from '../../src/registry-explorer/core/registry.schema';

describe('preview and component page links', () => {
  it('keeps preview URLs out of component page fields and labels preview links as previews', () => {
    const registry = registryFixture();
    const previewUrl = 'https://delta.example/preview.png';
    const componentPageUrl = 'https://delta.example/components/code-block';

    const [candidate] = searchComponentCandidates([registry], 'code block');
    const item = buildRegistryProfile(registry).sections[2]?.items?.[0];
    const related = buildRelatedComponents([registry], { registryName: '@delta', itemSlug: 'code-block' });
    const result = resolveRegistryItemDetailFromSummary([registry], '@delta', 'code-block');
    const body = { innerHTML: '' } as HTMLElement;

    expect(candidate?.componentPageUrl).toBe(componentPageUrl);
    expect(candidate?.componentPageUrl).not.toBe(previewUrl);
    expect(item?.componentPageUrl).toBe(componentPageUrl);
    expect(item?.componentPageUrl).not.toBe(previewUrl);
    expect(related).toEqual([]);
    expect(result.detail?.componentPageUrl).toBe(componentPageUrl);
    expect(result.detail?.componentPageUrl).not.toBe(previewUrl);

    renderItemDetailView({ innerHTML: '' } as HTMLElement, body, result, new Set());

    expect(body.innerHTML).toContain('Open preview');
    expect(body.innerHTML).toContain(`href="${previewUrl}"`);
    expect(body.innerHTML).toContain(`href="${componentPageUrl}"`);
    expect(body.innerHTML).not.toContain(`href="${previewUrl}" class="secondary-link" target="_blank" rel="noreferrer">Open component page`);
  });

  it('keeps related component page links grounded when a preview exists', () => {
    const registry = registryFixture(true);
    const [related] = buildRelatedComponents([registry], { registryName: '@delta', itemSlug: 'code-block' });

    expect(related).toEqual(expect.objectContaining({
      previewUrl: 'https://delta.example/related.png',
      componentPageUrl: 'https://delta.example/components/related-block',
    }));
  });
});

function registryFixture(includeRelated = false): Registry {
  return {
    name: '@delta',
    url: 'https://delta.example',
    description: 'Delta registry fixture.',
    primary_focus: ['support'],
    component_tags: ['code-block'],
    atlas: {
      aliases: [],
      coverageStatus: 'verified',
      confidence: 'high',
      notes: 'Fixture notes.',
      catalogStatus: 'available',
    },
    mirror: {
      officialName: '@delta',
      registryUrlTemplate: 'https://delta.example/r/{name}.json',
      sourceUrl: 'https://ui.shadcn.com/r/registries.json',
      syncedAt: '2026-06-27T00:00:00.000Z',
      upstreamCount: includeRelated ? 2 : 1,
      localCount: includeRelated ? 2 : 1,
      warnings: [],
    },
    itemSummaries: [
      {
        name: 'Code Block',
        slug: 'code-block',
        title: 'Code Block',
        description: 'Syntax highlighted code block.',
        type: 'registry:ui',
        category: 'code',
        componentTagsProposed: ['code-block'],
        source: 'registry-json',
        provenance: 'fixture',
        catalogStatus: 'available',
        confidence: 'high',
        routeEligible: true,
        rawItemUrl: 'https://delta.example/r/code-block.json',
        docsUrl: 'https://delta.example/components/code-block',
        previewUrl: 'https://delta.example/preview.png',
      },
      ...(includeRelated ? [{
        name: 'Related Block',
        slug: 'related-block',
        title: 'Related Block',
        type: 'registry:ui',
        category: 'code',
        componentTagsProposed: ['code-block'],
        source: 'registry-json',
        provenance: 'fixture',
        catalogStatus: 'available' as const,
        confidence: 'high' as const,
        routeEligible: true,
        rawItemUrl: 'https://delta.example/r/related-block.json',
        docsUrl: 'https://delta.example/components/related-block',
        previewUrl: 'https://delta.example/related.png',
      }] : []),
    ],
  };
}
