// Generated by OrchestKit Claude Plugin
// Created: 2026-08-25

import { afterEach, describe, expect, it, vi } from 'vitest';
import type { Registry } from '../../src/registry-explorer/core/registry.schema';
import { parseCatalogTaxonomy } from '../../src/registry-explorer/core/catalogTaxonomy';
import { initRegistryExplorer } from '../../src/registry-explorer/ui/shell';

const TEST_TAXONOMY = parseCatalogTaxonomy({
  version: 'v1',
  roots: [
    {
      id: 'application', label: 'Application', aliases: ['app'], what: 'Application surfaces',
      notFor: [], examples: [], children: [
        {
          id: 'application/app-shell', label: 'App Shell', aliases: ['workspace shell'],
          what: 'Application shell', notFor: [], examples: [], children: [],
        },
        {
          id: 'application/dashboard', label: 'Dashboard', aliases: [],
          what: 'Dashboard pages', notFor: [], examples: [], children: [],
        },
      ],
    },
    {
      id: 'ai', label: 'AI', aliases: [], what: 'AI surfaces',
      notFor: [], examples: [], children: [{
        id: 'ai/chat', label: 'Chat', aliases: ['ai chat'], what: 'AI chat',
        notFor: [], examples: [], children: [],
      }],
    },
    {
      id: 'controls', label: 'Controls', aliases: [], what: 'Controls',
      notFor: [], examples: [], children: [{
        id: 'controls/button', label: 'Button', aliases: [], what: 'Buttons',
        notFor: [], examples: [], children: [],
      }],
    },
  ],
});

interface FakeRoot {
  innerHTML: string;
  listeners: Map<string, ((event: any) => void)[]>;
  addEventListener(type: string, listener: (event: any) => void): void;
  insertAdjacentHTML(_position: string, html: string): void;
  dispatch(type: string, target: any, extra?: Record<string, unknown>): void;
  querySelectorAll(selector: string): any[];
}

describe('registry explorer shell interactions', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('keeps home navigation uncluttered and uses plain catalog vocabulary', () => {
    const home = setup('', '/Registry-Atlas/');
    expect(home.contentHeader.innerHTML).toContain('<h1>Browse shadcn registries.</h1>');
    expect(home.contentHeader.innerHTML).toContain('Browse components, templates, themes, and registries in one place.');
    expect(home.contentBody.innerHTML).toContain('<span>items</span>');
    expect(home.contentBody.innerHTML).toContain('<span>catalogs</span>');
    expect(home.contentBody.innerHTML).toContain('<span>registries</span>');
    expect(home.contentBody.innerHTML).not.toMatch(/indexed|tracked|evidence-backed|real registry/i);
    expect(home.aside.innerHTML).not.toContain('catalog-sidebar-summary');
    expect(home.aside.innerHTML).not.toContain('catalog-sidebar-routes');
    expect(home.aside.innerHTML).not.toContain('catalog-sidebar-filters');
    expect(home.aside.innerHTML).not.toContain('mobile-bottom-nav');
    expect(home.aside.innerHTML).not.toContain('mobile-browse-menu');

    const harness = setup('', '/Registry-Atlas/components');
    expect(harness.aside.innerHTML).toContain('class="desktop-browse-rail"');
    expect(harness.aside.innerHTML).toContain('data-browse-layout="grid"');
    expect(harness.aside.innerHTML).toContain('data-browse-layout="list"');
    expect(harness.aside.innerHTML).toContain('data-catalog-sort-value="name"');
    expect(harness.aside.innerHTML).toContain('shadcn directory');
    expect(harness.aside.innerHTML).not.toContain('data-catalog-registry-select');
    expect(harness.aside.innerHTML).not.toContain('<details');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-search');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-sort');
    expect(harness.aside.innerHTML).not.toContain('catalog-sidebar-summary');
  });

  it('routes top-level category rows into shareable first-class block filters', () => {
    const harness=setup('', '/Registry-Atlas/blocks', undefined, undefined, canonicalCatalogItems());
    expect(harness.aside.innerHTML).toContain('data-catalog-canonical-value="application"');
    expect(harness.aside.innerHTML).not.toContain('data-catalog-canonical-value="application/app-shell"');

    harness.aside.dispatch('click',target({
      'data-catalog-canonical-value':'application',
    }));

    expect(harness.location.pathname).toBe('/Registry-Atlas/blocks');
    expect(harness.location.search).toContain('canonical=application');
    expect(harness.aside.innerHTML).toMatch(/data-catalog-canonical-value="application"[\s\S]*?aria-pressed="true"/);
    expect(harness.contentBody.innerHTML).toContain('Free App Shell');
    expect(harness.contentBody.innerHTML).not.toContain('Paid AI Chat');
    expect(harness.contentBody.innerHTML).not.toContain('Dashboard Page');

    harness.aside.dispatch('click',target({
      'data-catalog-canonical-value':'application',
    }));
    expect(harness.location.search).not.toContain('canonical=');
  });

  it('keeps components, blocks, and pages as separate first-class collections', () => {
    const components=setup('', '/Registry-Atlas/components', undefined, undefined, canonicalCatalogItems());
    expect(components.contentBody.innerHTML).toContain('Button Basic');
    expect(components.contentBody.innerHTML).not.toContain('Free App Shell');
    expect(components.contentBody.innerHTML).not.toContain('Dashboard Page');

    const blocks=setup('', '/Registry-Atlas/blocks', undefined, undefined, canonicalCatalogItems());
    expect(blocks.contentBody.innerHTML).toContain('Free App Shell');
    expect(blocks.contentBody.innerHTML).toContain('Paid AI Chat');
    expect(blocks.contentBody.innerHTML).not.toContain('Dashboard Page');
    expect(blocks.contentBody.innerHTML).not.toContain('data-asset-kind-value="block"');

    const pages=setup('', '/Registry-Atlas/pages', undefined, undefined, canonicalCatalogItems());
    expect(pages.contentBody.innerHTML).toContain('Dashboard Page');
    expect(pages.contentBody.innerHTML).not.toContain('Free App Shell');
    expect(pages.contentBody.innerHTML).not.toContain('Button Basic');
  });

  it('shows Access only when explicit metadata exists and keeps it shareable', () => {
    const harness=setup('', '/Registry-Atlas/blocks', undefined, undefined, canonicalCatalogItems());

    expect(harness.aside.innerHTML).toContain('data-catalog-access-value="free"');
    expect(harness.aside.innerHTML).toContain('data-catalog-access-value="paid"');

    harness.aside.dispatch('click', target({
      'data-catalog-access-value': 'free',
    }));
    expect(harness.location.search).toContain('access=free');
    expect(harness.contentBody.innerHTML).toContain('Free App Shell');
    expect(harness.contentBody.innerHTML).not.toContain('Paid AI Chat');
    expect(harness.contentBody.innerHTML).toContain('Access: Free');
    expect(harness.aside.innerHTML).toMatch(/data-catalog-access-value="free"[\s\S]*?aria-pressed="true"/);

    harness.aside.dispatch('click', target({
      'data-catalog-access-value': 'free',
    }));
    expect(harness.location.search).not.toContain('access=');

    const noAccess=setup('', '/Registry-Atlas/blocks', undefined, undefined, canonicalCatalogItems().map(item => {
      const { access: _access, ...rest } = item;
      return rest;
    }));
    expect(noAccess.aside.innerHTML).not.toContain('data-catalog-access-value');
  });

  it('rehydrates canonical and access URL state on a first-class block route', () => {
    const harness=setup(
      '?canonical=application%2Fapp-shell&access=free',
      '/Registry-Atlas/blocks',
      undefined,
      undefined,
      canonicalCatalogItems(),
    );

    expect(harness.aside.innerHTML).toMatch(/data-catalog-canonical-value="application"[\s\S]*?aria-pressed="true"/);
    expect(harness.aside.innerHTML).toMatch(/data-catalog-access-value="free"[\s\S]*?aria-pressed="true"/);
    expect(harness.contentBody.innerHTML).toContain('Access: Free');
    expect(harness.contentBody.innerHTML).toContain('Free App Shell');
    expect(harness.contentBody.innerHTML).not.toContain('Paid AI Chat');
    expect(harness.contentBody.innerHTML).not.toContain('data-asset-kind-value="block"');
  });

  it('shows top-level canonical categories for source-flat registry items', () => {
    const harness=setup('', '/Registry-Atlas/@delta', undefined, undefined, canonicalCatalogItems());
    expect(harness.aside.innerHTML).toContain('data-catalog-canonical-value="application"');
    expect(harness.aside.innerHTML).toContain('>Application<');
    expect(harness.aside.innerHTML).not.toContain('>App Shell<');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-category-value="app-shell"');
  });

  it('uses the exemplar registry rail for layout, sort, and category rows', () => {
    const harness = setup('', '/Registry-Atlas/registries');
    expect(harness.aside.innerHTML).toContain('data-browse-layout="grid"');
    expect(harness.aside.innerHTML).toContain('data-browse-layout="list"');
    expect(harness.aside.innerHTML).toContain('data-registry-sort-value="item-count-desc"');
    expect(harness.aside.innerHTML).toContain('data-registry-asset-value');
    expect(harness.aside.innerHTML).toContain('shadcn directory');
    expect(harness.aside.innerHTML).not.toContain('Canonical category');
    expect(harness.contentBody.innerHTML).not.toContain('registry-directory-controls');

    harness.aside.dispatch('click', target({ 'data-browse-layout': 'list' }));
    expect(harness.location.search).toContain('layout=list');
    expect(harness.contentBody.innerHTML).toContain('registry-directory-grid-list');

    harness.aside.dispatch('click', target({ 'data-registry-sort-value': 'item-count-desc' }));
    expect(harness.location.search).toContain('registrySort=item-count-desc');

    harness.aside.dispatch('click', target({ 'data-registry-asset-value': 'component' }));
    expect(harness.location.search).toContain('asset=component');

    const reloaded = setup(
      '?layout=list&registrySort=item-count-desc&asset=component',
      '/Registry-Atlas/registries',
    );
    expect(reloaded.aside.innerHTML).toMatch(/data-browse-layout="list"[^>]*aria-pressed="true"/);
    expect(reloaded.aside.innerHTML).toMatch(/data-registry-sort-value="item-count-desc"[^>]*aria-pressed="true"/);
    expect(reloaded.aside.innerHTML).toMatch(/data-registry-asset-value="component"[^>]*aria-pressed="true"/);
    expect(reloaded.contentBody.innerHTML).toContain('registry-directory-grid-list');
  });

  it('opens a real author attribution, reloads its exact query and returns to authors',()=>{
    const harness=setup('','/Registry-Atlas/authors',undefined,'Source Author');
    expect(harness.contentBody.innerHTML).toContain('data-author-select="Source Author"');
    harness.contentBody.dispatch('click',target({'data-author-select':'Source Author'}));
    expect(harness.location.search).toContain('author=Source+Author');
    expect(harness.contentHeader.innerHTML).toContain('<h1>Source Author</h1>');
    expect(harness.contentBody.innerHTML).toContain('data-view-item-registry="@delta"');
    harness.contentBody.dispatch('click',target({'data-author-clear':''}));
    expect(harness.location.search).not.toContain('author=');
    expect(harness.contentBody.innerHTML).toContain('data-author-select="Source Author"');
    const reloaded=setup('?author=Source+Author','/Registry-Atlas/authors',undefined,'Source Author');
    expect(reloaded.contentBody.innerHTML).toContain('data-view-item-registry="@delta"');
  });
  it('renders the source-attribution authors route even with no indexed named authors',()=>{
    const harness=setup('','/Registry-Atlas/authors');
    expect(harness.contentHeader.innerHTML).toContain('<h1>Authors</h1>');
    expect(harness.contentBody.innerHTML).toContain('No attributed components');
    expect(harness.contentBody.innerHTML).not.toContain('Top Authors');
  });
  it('retired routes render not-found instead of a fake browse surface', () => {
    for (const path of ['/components/featured', '/components/newest']) {
      const harness = setup('', `/Registry-Atlas${path}`);
      expect(harness.contentHeader.innerHTML).toContain('Route not found');
      expect(harness.contentBody.innerHTML).not.toContain('data-view-item-registry');
    }
  });

  it('labels icon routes as registry-backed Icons without the retired asset terminology', () => {
    const root = setup('', '/Registry-Atlas/icons');
    expect(root.contentHeader.innerHTML).toContain('<h1>Icons</h1>');
    expect(root.contentHeader.innerHTML).toContain('not a searchable glyph index');

    const category = setup('', '/Registry-Atlas/icons/c/icons');
    expect(category.contentHeader.innerHTML).toContain('Icons / Category');
    expect(category.contentHeader.innerHTML).not.toContain('Icon-related assets');

    const family = setup('', '/Registry-Atlas/icons/missing-family');
    expect(family.contentHeader.innerHTML).toContain('Icons · missing-family');
    expect(family.contentHeader.innerHTML).not.toContain('Icon-related assets');
  });

  it('uses the single global search for registry discovery without duplicating controls in results', () => {
    const harness = setup('', '/Registry-Atlas/components');

    expect(harness.aside.innerHTML).not.toContain('data-catalog-registry-select');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-registry-select');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-search');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-sort');
    expect(harness.contentBody.innerHTML).not.toContain('<details');

    harness.searchInput.value = '@delta';
    harness.searchInput.dispatch('input', {});
    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/%40delta');
    expect(harness.contentBody.innerHTML).toContain('@delta');
  });

  it('routes header copy actions and announces successful feedback', async () => {
    const clipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
    const harness = setup('?view=compare');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentHeader.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(clipboard.writeText).toHaveBeenCalledWith(harness.location.href);
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
    expect(harness.contentHeader.innerHTML).toContain('aria-live="polite"');
    expect(harness.contentHeader.innerHTML).not.toContain(`<code>${harness.location.href}</code>`);
  });

  it('announces clipboard denial on the item surface', async () => {
    const clipboard = { writeText: vi.fn().mockRejectedValue(new Error('denied')) };
    const harness = setup('?view=item&registry=%40delta&item=code-block');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentBody.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(harness.contentHeader.innerHTML).toContain('Clipboard unavailable');
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
  });


  it('clears copied prompt feedback when navigating to another route', async () => {
    const clipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
    const harness = setup('?view=item&registry=%40delta&item=code-block');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentBody.dispatch('click', target({ 'data-copy-text': 'LONG AGENT PROMPT', 'data-copy-label': 'Agent prompt copied' }));
    await Promise.resolve();
    await Promise.resolve();
    expect(harness.contentHeader.innerHTML).toContain('Agent prompt copied');
    expect(harness.contentHeader.innerHTML).not.toContain('LONG AGENT PROMPT');

    harness.tabs[2].dispatch('click', {});
    expect(harness.contentHeader.innerHTML).not.toContain('Agent prompt copied');
    expect(harness.contentHeader.innerHTML).not.toContain('LONG AGENT PROMPT');
  });

  it('ignores stale profile fields when the URL requests Compare', () => {
    const harness = setup(
      '?view=compare&registry=%40delta&candidate=%40delta%3Acode-block&item=code-block',
    );

    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
    expect(harness.contentHeader.innerHTML).not.toContain('Profile link');
  });

  it('rehydrates the view and search input on popstate', () => {
    const harness = setup('?view=discover&q=button');
    const popstate = harness.windowListeners.get('popstate')?.[0];
    expect(popstate).toBeTypeOf('function');

    harness.location.search = '?view=compare&q=table';
    popstate?.({ state: null });

    expect(harness.searchInput.value).toBe('table');
    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
    expect(harness.tabs[2].getAttribute('aria-current')).toBe('page');
  });

  it('writes component searches to the canonical path and renders only real index results', () => {
    const harness = setup('?view=discover');
    harness.searchInput.value = 'catalog only';
    harness.searchInput.dispatch('input', {});

    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/catalog%20only');
    expect(harness.contentBody.innerHTML).toContain('Catalog Only');
    expect(harness.contentBody.innerHTML).toContain('data-view-item-slug="catalog-only"');
    expect(harness.contentBody.innerHTML).not.toContain('Copy install');
  });

  it('rehydrates shareable catalog facets, sort, and page state without exposing review controls', () => {
    const harness = setup(
      '?page=2&sort=type&registry=%40delta&type=registry%3Aui&reviewed=unreviewed',
      '/Registry-Atlas/components',
    );

    expect(harness.aside.innerHTML).not.toContain('data-catalog-registry-select');
    expect(harness.aside.innerHTML).toMatch(/data-catalog-sort-value="name"[\s\S]*?aria-pressed="true"/);
    expect(harness.contentBody.innerHTML).toContain('Registry: @delta');
    expect(harness.contentBody.innerHTML).not.toContain('data-catalog-reviewed');
    expect(harness.location.search).toContain('page=2');
    expect(harness.location.search).toContain('registry=%40delta');
    expect(harness.location.search).not.toContain('sort=type');
    expect(harness.location.search).not.toContain('type=');
    expect(harness.location.search).not.toContain('reviewed=');
  });

  it('writes registry-name search to the canonical search path and resets paging', () => {
    const harness = setup('?page=3', '/Registry-Atlas/components');

    harness.searchInput.value = '@delta';
    harness.searchInput.dispatch('input', {});

    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/%40delta');
    expect(harness.location.search).toBe('');
    expect(harness.contentBody.innerHTML).toContain('@delta');
  });

  it('writes component pagination to the shareable URL', () => {
    const harness = setup('', '/Registry-Atlas/components');

    harness.contentBody.dispatch('click', target({ 'data-discovery-page': '2' }));

    expect(harness.location.search).toBe('?page=2');
  });

  it('retains focus while toggling a Compare option twice', () => {
    const harness = setup('?view=compare');
    const option = target({ 'data-compare-registry': '@delta' });
    const replacement = target({ 'data-compare-registry': '@delta' });
    harness.contentBody.querySelectorAll = selector =>
      selector.includes('[data-compare-registry]') ? [replacement] : [];

    harness.contentBody.dispatch('click', option);
    expect(replacement.focus).toHaveBeenCalled();
    expect(harness.contentBody.innerHTML).toContain('aria-pressed="true"');

    harness.contentBody.dispatch('click', option);
    expect(harness.contentBody.innerHTML).toContain('aria-pressed="false"');
  });

  it('retains focus while toggling a top-level canonical category row', () => {
    const harness = setup('', '/Registry-Atlas/blocks', undefined, undefined, canonicalCatalogItems());
    const option = target({ 'data-catalog-canonical-value': 'application' });
    const replacement = target({ 'data-catalog-canonical-value': 'application' });
    harness.aside.querySelectorAll = selector =>
      selector.includes('[data-catalog-canonical-value]') ? [replacement] : [];

    harness.aside.dispatch('click', option);

    expect(replacement.focus).toHaveBeenCalled();
    expect(harness.aside.innerHTML).toMatch(/data-catalog-canonical-value="application"[\s\S]*?aria-pressed="true"/);
  });

  it('does not render the retired inferred component facet system', () => {
    const harness = setup('?view=discover&component=code-block');

    expect(harness.contentBody.innerHTML).not.toContain('data-facet-add-dimension');
    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-id');
    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/code-block');
  });

  it('keeps the registry homepage in the header of every route tied to a known library', () => {
    for (const path of [
      '/Registry-Atlas/@delta',
      '/Registry-Atlas/@delta/components/catalog-only',
      '/Registry-Atlas/@delta/templates/catalog-only',
      '/Registry-Atlas/@delta/themes/catalog-only',
      '/Registry-Atlas/@delta/components/missing-component',
      '/Registry-Atlas/icons/delta',
    ]) {
      const harness = setup('', path);
      const header = harness.contentHeader.innerHTML;
      expect(header, path).toContain('href="https://delta.example/"');
      expect(header, path).toContain('>Visit registry homepage</a>');
      expect(header, path).toContain('target="_blank" rel="noreferrer"');
      expect(header.match(/>Visit registry homepage<\/a>/g), path).toHaveLength(1);
    }
    for (const path of [
      '/Registry-Atlas/',
      '/Registry-Atlas/registries',
      '/Registry-Atlas/components',
      '/Registry-Atlas/icons',
      '/Registry-Atlas/icons/nonexistent',
      '/Registry-Atlas/compare',
      '/Registry-Atlas/@missing/components/button',
    ]) {
      const harness = setup('', path);
      expect(harness.contentHeader.innerHTML, path).not.toContain('>Visit registry homepage</a>');
    }
  });

  it('keeps registry profiles deep-linkable with canonical registry paths', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch('click', target({ 'data-profile-registry': '@delta' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta');
    expect(harness.location.search).toBe('');
    expect(harness.history.pushes.at(-1)).toContain('/Registry-Atlas/@delta');

    const reloaded = setup('', '/Registry-Atlas/@delta');
    expect(reloaded.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(reloaded.contentBody.innerHTML).toContain('<h2>Items</h2>');
  });

  it('keeps registry navigation on Registries and returns there from an item', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'code-block' }),
    );
    harness.contentHeader.dispatch('click', target({ 'data-back-from-item': '' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>Registries</h1>');
  });

  it('uses push history for navigation but not search typing', () => {
    const harness = setup('?view=discover');
    const initialPushes = harness.history.pushes.length;

    harness.tabs[1].dispatch('click', {});
    expect(harness.history.pushes.length).toBe(initialPushes + 1);

    const pushesAfterNavigation = harness.history.pushes.length;
    harness.searchInput.value = 'button';
    harness.searchInput.dispatch('input', {});
    expect(harness.history.pushes.length).toBe(pushesAfterNavigation);
  });

  it('opens catalogue cards directly instead of using browse quick-peeks', () => {
    const harness = setup('?view=discover');

    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-id');
    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'catalog-only' }),
    );

    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta/components/catalog-only');
    expect(harness.contentHeader.innerHTML).toContain('Catalog Only');
  });

  it('searches and routes an indexed-only catalog item through the shell', () => {
    const harness = setup('?view=discover');

    harness.searchInput.value = 'catalog only';
    harness.searchInput.dispatch('input', {});

    expect(harness.contentBody.innerHTML).toContain('Catalog Only');
    expect(harness.contentBody.innerHTML).toContain('data-view-item-slug="catalog-only"');
    expect(harness.contentBody.innerHTML).not.toContain('Copy install');

    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'catalog-only' }),
    );

    expect(harness.contentHeader.innerHTML).toContain('Catalog Only');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta/components/catalog-only');
  });

  it('lazily upgrades indexed-only detail from the upstream item JSON and caches it', async () => {
    const fetchImpl = vi.fn(async (_input: RequestInfo | URL) => jsonResponse({
      name: 'catalog-only',
      title: 'Catalog Only Loaded',
      description: 'Loaded from the upstream registry item JSON.',
      type: 'registry:ui',
      dependencies: ['react'],
      files: [{ path: 'registry/catalog-only.tsx', type: 'registry:ui' }],
    }));
    const harness = setup(
      '',
      '/Registry-Atlas/@delta/components/catalog-only',
      fetchImpl as typeof fetch,
    );

    expect(harness.contentBody.innerHTML).toContain('No description is available.');

    await vi.waitFor(() => {
      expect(harness.contentHeader.innerHTML).toContain('Catalog Only Loaded');
      expect(harness.contentBody.innerHTML).toContain('Loaded from the upstream registry item JSON.');
      expect(harness.contentBody.innerHTML).toContain('<code>react</code>');
    });
    expect(fetchImpl).toHaveBeenCalledTimes(2);
    expect(String(fetchImpl.mock.calls[0]?.[0])).toContain('/data/registry-details.sqlite.gz');

    harness.contentBody.dispatch('click', target({ 'data-back-from-item': '' }));
    harness.contentBody.dispatch('click', target({
      'data-view-item-registry': '@delta',
      'data-view-item-slug': 'catalog-only',
    }));

    await vi.waitFor(() => {
      expect(harness.contentHeader.innerHTML).toContain('Catalog Only Loaded');
    });
    expect(fetchImpl).toHaveBeenCalledTimes(2);
  });

  it('migrates a legacy registry deep link to the canonical registry path', () => {
    const harness = setup('?view=registries&registry=%40delta');

    expect(harness.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta');
    expect(harness.location.search).toBe('');
  });

});

function setup(
  search: string,
  pathname = '/Registry-Atlas/',
  fetchImpl: typeof fetch = async () => jsonResponse({
    name: 'catalog-only',
    type: 'registry:ui',
    dependencies: [],
    files: [],
  }),
  attributedAuthor?: string,
  catalogItems?: any[],
) {
  const location = {
    pathname,
    search,
    hash: '',
    href: `http://localhost${pathname}${search}`,
  };
  const windowListeners = new Map<string, ((event: any) => void)[]>();
  const history = {
    pushes: [] as string[],
    replaces: [] as string[],
    pushState(_state: unknown, _title: string, next: string) {
      this.pushes.push(next);
      updateLocation(next);
    },
    replaceState(_state: unknown, _title: string, next: string) {
      this.replaces.push(next);
      updateLocation(next);
    },
  };
  function updateLocation(next: string): void {
    const url = new URL(next, 'http://localhost');
    location.pathname = url.pathname;
    location.search = url.search;
    location.hash = url.hash;
    location.href = url.href;
  }
  vi.stubGlobal('window', {
    location,
    history,
    addEventListener(type: string, listener: (event: any) => void) {
      const listeners = windowListeners.get(type) ?? [];
      listeners.push(listener);
      windowListeners.set(type, listeners);
    },
  });

  const aside = root();
  const contentHeader = root();
  const contentBody = root();
  const tabs = [tab('discover'), tab('registries'), tab('compare')];
  const searchInput = input();
  initRegistryExplorer({
    registries: [registryFixture()],
    taxonomy: TEST_TAXONOMY,
    catalogIndex: {
      meta: { registry_count: 1, item_count: 1 },
      registries: {
        '@delta': catalogItems ?? [{ name: 'catalog-only', title: 'Catalog Only', type: 'registry:ui', categories: ['code'], ...(attributedAuthor?{author:attributedAuthor}:{}) }],
      },
    },
    mirrorMeta: {
      source_url: 'https://atlas.example/source',
      synced_at: '2026-08-25T00:00:00.000Z',
      upstream_count: 1,
      registry_count: 1,
      local_count: 1,
      validation_status: 'valid',
      report_path: 'report.json',
    },
    mirrorWarnings: [],
    fetchImpl,
    roots: {
      aside: aside as unknown as HTMLElement,
      contentHeader: contentHeader as unknown as HTMLElement,
      contentBody: contentBody as unknown as HTMLElement,
      tabs: tabs as unknown as NodeListOf<Element>,
      searchInput: searchInput as unknown as HTMLInputElement,
    },
  });

  return { aside, contentHeader, contentBody, tabs, searchInput, location, history, windowListeners };
}

function root(): FakeRoot {
  return {
    innerHTML: '',
    listeners: new Map(),
    addEventListener(type, listener) {
      const listeners = this.listeners.get(type) ?? [];
      listeners.push(listener);
      this.listeners.set(type, listeners);
    },
    insertAdjacentHTML(_position, html) {
      this.innerHTML += html;
    },
    dispatch(type, target, extra = {}) {
      this.listeners.get(type)?.forEach(listener => listener({ target, preventDefault: vi.fn(), ...extra }));
    },
    querySelectorAll: () => [],
  };
}

function tab(view: string) {
  const attrs: Record<string, string> = { 'data-view': view };
  const item = root() as FakeRoot & {
    getAttribute: (name: string) => string | null;
    setAttribute: (name: string, value: string) => void;
    removeAttribute: (name: string) => void;
    classList: { toggle: () => void };
  };
  item.getAttribute = name => attrs[name] ?? null;
  item.setAttribute = (name, value) => { attrs[name] = value; };
  item.removeAttribute = name => { delete attrs[name]; };
  item.classList = { toggle: vi.fn() };
  return item;
}

function jsonResponse(data: unknown): Response {
  return {
    ok: true,
    status: 200,
    statusText: 'OK',
    json: async () => data,
  } as Response;
}

function input() {
  const item = root() as FakeRoot & { value: string };
  item.value = '';
  return item;
}

function target(attributes: Record<string, string>) {
  const focus = vi.fn();
  return {
    focus,
    value: attributes.value ?? '',
    classList: {
      contains: (name: string) => (attributes.class ?? '').split(' ').includes(name),
    },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: (selector: string) => {
      if (selector.includes('.component-peek-trigger') && !attributes.class?.split(' ').includes('component-peek-trigger')) return null;
      const names = [...selector.matchAll(/\[([a-zA-Z0-9_-]+)/g)].map(match => match[1]);
      return names.some(name => name in attributes) ? targetWithFocus(attributes, focus) : null;
    },
  };
}

function targetWithFocus(attributes: Record<string, string>, focus: ReturnType<typeof vi.fn>) {
  return {
    focus,
    value: attributes.value ?? '',
    classList: { contains: (name: string) => (attributes.class ?? '').split(' ').includes(name) },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: () => null,
  };
}

function canonicalCatalogItems(): any[] {
  return [
    {
      name: 'free-app-shell',
      title: 'Free App Shell',
      description: 'A flat-source application shell.',
      type: 'registry:block',
      kind: 'block',
      canonical: {
        taxonomyVersion: 'v1',
        primary: 'application/app-shell',
        path: ['application', 'application/app-shell'],
      },
      access: { normalized: 'free', sourceLabel: 'Free' },
    },
    {
      name: 'paid-ai-chat',
      title: 'Paid AI Chat',
      description: 'An AI chat surface.',
      type: 'registry:block',
      kind: 'block',
      canonical: {
        taxonomyVersion: 'v1',
        primary: 'ai/chat',
        path: ['ai', 'ai/chat'],
      },
      access: { normalized: 'paid', sourceLabel: 'Pro' },
    },
    {
      name: 'button-basic',
      title: 'Button Basic',
      type: 'registry:ui',
      kind: 'component',
      canonical: {
        taxonomyVersion: 'v1',
        primary: 'controls/button',
        path: ['controls', 'controls/button'],
      },
    },
    {
      name: 'dashboard-page',
      title: 'Dashboard Page',
      type: 'registry:page',
      kind: 'page',
      canonical: {
        taxonomyVersion: 'v1',
        primary: 'application/dashboard',
        path: ['application', 'application/dashboard'],
      },
    },
  ];
}

function registryFixture(): Registry {
  return {
    name: '@delta',
    url: 'https://delta.example',
    description: 'Delta registry fixture.',
    atlas: {
      aliases: [],
      coverageStatus: 'verified',
      confidence: 'high',
      notes: 'Fixture notes.',
      catalogStatus: 'available',
      comparisonEvidence: 'catalog',
      catalogItemCount: 1,
      catalogEvidenceUrl: 'https://delta.example/r/registry.json',
    },
    mirror: {
      officialName: '@delta',
      registryUrlTemplate: 'https://delta.example/r/{name}.json',
      sourceUrl: 'https://atlas.example/source',
      syncedAt: '2026-09-28T00:00:00.000Z',
      upstreamCount: 1,
      localCount: 1,
      warnings: [],
    },
    itemSummaries: [{
      name: 'Code Block',
      slug: 'code-block',
      title: 'Code Block',
      description: 'Syntax highlighted code block.',
      type: 'registry:ui',
      category: 'code',
      source: 'registry-json',
      provenance: 'fixture',
      catalogStatus: 'available',
      confidence: 'high',
      routeEligible: true,
      rawItemUrl: 'https://delta.example/r/code-block.json',
      docsUrl: 'https://delta.example/components/code-block',
      installCommand: 'npx shadcn add @delta/code-block',
      viewCommand: 'npx shadcn view @delta/code-block',
      dependencies: [],
      registryDependencies: [],
      files: [],
    }],
  };
}
