// Generated by OrchestKit Claude Plugin
// Created: 2026-08-25

import { afterEach, describe, expect, it, vi } from 'vitest';
import type { Registry } from '../../src/registry-explorer/core/registry.schema';
import { initRegistryExplorer } from '../../src/registry-explorer/ui/shell';

interface FakeRoot {
  innerHTML: string;
  listeners: Map<string, ((event: any) => void)[]>;
  addEventListener(type: string, listener: (event: any) => void): void;
  insertAdjacentHTML(_position: string, html: string): void;
  dispatch(type: string, target: any, extra?: Record<string, unknown>): void;
  querySelectorAll(selector: string): any[];
}

describe('registry explorer shell interactions', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('routes header copy actions and announces successful feedback', async () => {
    const clipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
    const harness = setup('?view=compare');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentHeader.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(clipboard.writeText).toHaveBeenCalledWith(harness.location.href);
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
    expect(harness.contentHeader.innerHTML).toContain('aria-live="polite"');
    expect(harness.contentHeader.innerHTML).not.toContain(`<code>${harness.location.href}</code>`);
  });

  it('announces clipboard denial on the item surface', async () => {
    const clipboard = { writeText: vi.fn().mockRejectedValue(new Error('denied')) };
    const harness = setup('?view=item&registry=%40delta&item=code-block');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentBody.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(harness.contentHeader.innerHTML).toContain('Clipboard unavailable');
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
  });


  it('clears copied prompt feedback when navigating to another route', async () => {
    const clipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
    const harness = setup('?view=item&registry=%40delta&item=code-block');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentBody.dispatch('click', target({ 'data-copy-text': 'LONG AGENT PROMPT', 'data-copy-label': 'Agent prompt copied' }));
    await Promise.resolve();
    await Promise.resolve();
    expect(harness.contentHeader.innerHTML).toContain('Agent prompt copied');
    expect(harness.contentHeader.innerHTML).not.toContain('LONG AGENT PROMPT');

    harness.tabs[2].dispatch('click', {});
    expect(harness.contentHeader.innerHTML).not.toContain('Agent prompt copied');
    expect(harness.contentHeader.innerHTML).not.toContain('LONG AGENT PROMPT');
  });

  it('ignores stale profile fields when the URL requests Compare', () => {
    const harness = setup(
      '?view=compare&registry=%40delta&candidate=%40delta%3Acode-block&item=code-block',
    );

    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
    expect(harness.contentHeader.innerHTML).not.toContain('Profile link');
  });

  it('rehydrates the view and search input on popstate', () => {
    const harness = setup('?view=discover&q=button');
    const popstate = harness.windowListeners.get('popstate')?.[0];
    expect(popstate).toBeTypeOf('function');

    harness.location.search = '?view=compare&q=table';
    popstate?.({ state: null });

    expect(harness.searchInput.value).toBe('table');
    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
    expect(harness.tabs[2].getAttribute('aria-current')).toBe('page');
  });

  it('writes component searches to the canonical path and renders only real index results', () => {
    const harness = setup('?view=discover');
    harness.searchInput.value = 'catalog only';
    harness.searchInput.dispatch('input', {});

    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/catalog%20only');
    expect(harness.contentBody.innerHTML).toContain('Catalog Only');
    expect(harness.contentBody.innerHTML).toContain('data-view-item-slug="catalog-only"');
    expect(harness.contentBody.innerHTML).not.toContain('Copy install');
  });

  it('retains focus while toggling a Compare option twice', () => {
    const harness = setup('?view=compare');
    const option = target({ 'data-compare-registry': '@delta' });
    const replacement = target({ 'data-compare-registry': '@delta' });
    harness.contentBody.querySelectorAll = selector =>
      selector.includes('[data-compare-registry]') ? [replacement] : [];

    harness.contentBody.dispatch('click', option);
    expect(replacement.focus).toHaveBeenCalled();
    expect(harness.contentBody.innerHTML).toContain('aria-pressed="true"');

    harness.contentBody.dispatch('click', option);
    expect(harness.contentBody.innerHTML).toContain('aria-pressed="false"');
  });

  it('does not render the retired inferred component facet system', () => {
    const harness = setup('?view=discover&component=code-block');

    expect(harness.contentBody.innerHTML).not.toContain('data-facet-add-dimension');
    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-id');
    expect(harness.location.pathname).toBe('/Registry-Atlas/components/s/code-block');
  });

  it('keeps registry profiles deep-linkable with canonical registry paths', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch('click', target({ 'data-profile-registry': '@delta' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta');
    expect(harness.location.search).toBe('');
    expect(harness.history.pushes.at(-1)).toContain('/Registry-Atlas/@delta');

    const reloaded = setup('', '/Registry-Atlas/@delta');
    expect(reloaded.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(reloaded.contentBody.innerHTML).toContain('Catalog components');
  });

  it('keeps registry navigation on Registries and returns there from an item', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'code-block' }),
    );
    harness.contentHeader.dispatch('click', target({ 'data-back-from-item': '' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>Registries</h1>');
  });

  it('uses push history for navigation but not search typing', () => {
    const harness = setup('?view=discover');
    const initialPushes = harness.history.pushes.length;

    harness.tabs[1].dispatch('click', {});
    expect(harness.history.pushes.length).toBe(initialPushes + 1);

    const pushesAfterNavigation = harness.history.pushes.length;
    harness.searchInput.value = 'button';
    harness.searchInput.dispatch('input', {});
    expect(harness.history.pushes.length).toBe(pushesAfterNavigation);
  });

  it('opens catalogue cards directly instead of using browse quick-peeks', () => {
    const harness = setup('?view=discover');

    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-id');
    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'catalog-only' }),
    );

    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta/components/catalog-only');
    expect(harness.contentHeader.innerHTML).toContain('Catalog Only');
  });

  it('searches and routes an indexed-only catalog item through the shell', () => {
    const harness = setup('?view=discover');

    harness.searchInput.value = 'catalog only';
    harness.searchInput.dispatch('input', {});

    expect(harness.contentBody.innerHTML).toContain('Catalog Only');
    expect(harness.contentBody.innerHTML).toContain('data-view-item-slug="catalog-only"');
    expect(harness.contentBody.innerHTML).not.toContain('Copy install');

    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'catalog-only' }),
    );

    expect(harness.contentHeader.innerHTML).toContain('Catalog Only');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta/components/catalog-only');
  });

  it('migrates a legacy registry deep link to the canonical registry path', () => {
    const harness = setup('?view=registries&registry=%40delta');

    expect(harness.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(harness.location.pathname).toBe('/Registry-Atlas/@delta');
    expect(harness.location.search).toBe('');
  });

});

function setup(search: string, pathname = '/Registry-Atlas/') {
  const location = {
    pathname,
    search,
    hash: '',
    href: `http://localhost${pathname}${search}`,
  };
  const windowListeners = new Map<string, ((event: any) => void)[]>();
  const history = {
    pushes: [] as string[],
    replaces: [] as string[],
    pushState(_state: unknown, _title: string, next: string) {
      this.pushes.push(next);
      updateLocation(next);
    },
    replaceState(_state: unknown, _title: string, next: string) {
      this.replaces.push(next);
      updateLocation(next);
    },
  };
  function updateLocation(next: string): void {
    const url = new URL(next, 'http://localhost');
    location.pathname = url.pathname;
    location.search = url.search;
    location.hash = url.hash;
    location.href = url.href;
  }
  vi.stubGlobal('window', {
    location,
    history,
    addEventListener(type: string, listener: (event: any) => void) {
      const listeners = windowListeners.get(type) ?? [];
      listeners.push(listener);
      windowListeners.set(type, listeners);
    },
  });

  const aside = root();
  const contentHeader = root();
  const contentBody = root();
  const tabs = [tab('discover'), tab('registries'), tab('compare')];
  const searchInput = input();
  initRegistryExplorer({
    registries: [registryFixture()],
    catalogIndex: {
      meta: { registry_count: 1, item_count: 1 },
      registries: {
        '@delta': [{ name: 'catalog-only', title: 'Catalog Only', type: 'registry:ui' }],
      },
    },
    mirrorMeta: {
      source_url: 'https://atlas.example/source',
      synced_at: '2026-08-25T00:00:00.000Z',
      upstream_count: 1,
      registry_count: 1,
      local_count: 1,
      validation_status: 'valid',
      report_path: 'report.json',
    },
    mirrorWarnings: [],
    roots: {
      aside: aside as unknown as HTMLElement,
      contentHeader: contentHeader as unknown as HTMLElement,
      contentBody: contentBody as unknown as HTMLElement,
      tabs: tabs as unknown as NodeListOf<Element>,
      searchInput: searchInput as unknown as HTMLInputElement,
    },
  });

  return { aside, contentHeader, contentBody, tabs, searchInput, location, history, windowListeners };
}

function root(): FakeRoot {
  return {
    innerHTML: '',
    listeners: new Map(),
    addEventListener(type, listener) {
      const listeners = this.listeners.get(type) ?? [];
      listeners.push(listener);
      this.listeners.set(type, listeners);
    },
    insertAdjacentHTML(_position, html) {
      this.innerHTML += html;
    },
    dispatch(type, target, extra = {}) {
      this.listeners.get(type)?.forEach(listener => listener({ target, preventDefault: vi.fn(), ...extra }));
    },
    querySelectorAll: () => [],
  };
}

function tab(view: string) {
  const attrs: Record<string, string> = { 'data-view': view };
  const item = root() as FakeRoot & {
    getAttribute: (name: string) => string | null;
    setAttribute: (name: string, value: string) => void;
    removeAttribute: (name: string) => void;
    classList: { toggle: () => void };
  };
  item.getAttribute = name => attrs[name] ?? null;
  item.setAttribute = (name, value) => { attrs[name] = value; };
  item.removeAttribute = name => { delete attrs[name]; };
  item.classList = { toggle: vi.fn() };
  return item;
}

function input() {
  const item = root() as FakeRoot & { value: string };
  item.value = '';
  return item;
}

function target(attributes: Record<string, string>) {
  const focus = vi.fn();
  return {
    focus,
    classList: {
      contains: (name: string) => (attributes.class ?? '').split(' ').includes(name),
    },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: (selector: string) => {
      if (selector.includes('.component-peek-trigger') && !attributes.class?.split(' ').includes('component-peek-trigger')) return null;
      const names = [...selector.matchAll(/\[([a-zA-Z0-9_-]+)/g)].map(match => match[1]);
      return names.some(name => name in attributes) ? targetWithFocus(attributes, focus) : null;
    },
  };
}

function targetWithFocus(attributes: Record<string, string>, focus: ReturnType<typeof vi.fn>) {
  return {
    focus,
    classList: { contains: (name: string) => (attributes.class ?? '').split(' ').includes(name) },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: () => null,
  };
}

function registryFixture(): Registry {
  return {
    name: '@delta',
    url: 'https://delta.example',
    description: 'Delta registry fixture.',
    primary_focus: ['support'],
    component_tags: ['code-block'],
    atlas: {
      aliases: [],
      coverageStatus: 'verified',
      confidence: 'high',
      notes: 'Fixture notes.',
      catalogStatus: 'available',
      comparisonEvidence: 'catalog',
      catalogItemCount: 1,
      catalogEvidenceUrl: 'https://delta.example/r/registry.json',
    },
    mirror: {
      officialName: '@delta',
      registryUrlTemplate: 'https://delta.example/r/{name}.json',
      sourceUrl: 'https://atlas.example/source',
      syncedAt: '2026-09-28T00:00:00.000Z',
      upstreamCount: 1,
      localCount: 1,
      warnings: [],
    },
    itemSummaries: [{
      name: 'Code Block',
      slug: 'code-block',
      title: 'Code Block',
      description: 'Syntax highlighted code block.',
      type: 'registry:ui',
      category: 'code',
      componentTagsProposed: ['code-block'],
      source: 'registry-json',
      provenance: 'fixture',
      catalogStatus: 'available',
      confidence: 'high',
      routeEligible: true,
      rawItemUrl: 'https://delta.example/r/code-block.json',
      docsUrl: 'https://delta.example/components/code-block',
      previewUrl: 'https://delta.example/preview.png',
      installCommand: 'npx shadcn add @delta/code-block',
      viewCommand: 'npx shadcn view @delta/code-block',
      dependencies: [],
      registryDependencies: [],
      files: [],
    }],
  };
}
