// Generated by OrchestKit Claude Plugin
// Created: 2026-08-25

import { afterEach, describe, expect, it, vi } from 'vitest';
import type { Registry } from '../../src/registry-explorer/core/registry.schema';
import { initRegistryExplorer } from '../../src/registry-explorer/ui/shell';

interface FakeRoot {
  innerHTML: string;
  listeners: Map<string, ((event: any) => void)[]>;
  addEventListener(type: string, listener: (event: any) => void): void;
  insertAdjacentHTML(_position: string, html: string): void;
  dispatch(type: string, target: any, extra?: Record<string, unknown>): void;
  querySelectorAll(selector: string): any[];
}

describe('registry explorer shell interactions', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('routes header copy actions and announces successful feedback', async () => {
    const clipboard = { writeText: vi.fn().mockResolvedValue(undefined) };
    const harness = setup('?view=compare');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentHeader.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(clipboard.writeText).toHaveBeenCalledWith(harness.location.href);
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
    expect(harness.contentHeader.innerHTML).toContain('aria-live="polite"');
  });

  it('announces clipboard denial on the item surface', async () => {
    const clipboard = { writeText: vi.fn().mockRejectedValue(new Error('denied')) };
    const harness = setup('?view=item&registry=%40delta&item=code-block');
    vi.stubGlobal('navigator', { clipboard });

    harness.contentBody.dispatch('click', target({ 'data-copy-current-url': '' }));
    await Promise.resolve();
    await Promise.resolve();

    expect(harness.contentHeader.innerHTML).toContain('Clipboard unavailable');
    expect(harness.contentHeader.innerHTML).toContain('role="status"');
  });

  it('ignores stale profile fields when the URL requests Compare', () => {
    const harness = setup(
      '?view=compare&registry=%40delta&candidate=%40delta%3Acode-block&item=code-block',
    );

    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
    expect(harness.contentHeader.innerHTML).not.toContain('Profile link');
  });

  it('rehydrates the view and search input on popstate', () => {
    const harness = setup('?view=discover&q=button');
    const popstate = harness.windowListeners.get('popstate')?.[0];
    expect(popstate).toBeTypeOf('function');

    harness.location.search = '?view=compare&q=table';
    popstate?.({ state: null });

    expect(harness.searchInput.value).toBe('table');
    expect(harness.contentHeader.innerHTML).toContain('<h1>Compare</h1>');
  });

  it('keeps registry profiles deep-linkable from Registries', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch('click', target({ 'data-profile-registry': '@delta' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
    expect(harness.location.search).toContain('registry=%40delta');
    expect(harness.history.pushes.at(-1)).toContain('registry=%40delta');

    const reloaded = setup('?view=registries&registry=%40delta');
    expect(reloaded.contentHeader.innerHTML).toContain('<h1>@delta</h1>');
  });

  it('keeps registry navigation on Registries and returns there from an item', () => {
    const harness = setup('?view=registries');

    harness.contentBody.dispatch(
      'click',
      target({ 'data-view-item-registry': '@delta', 'data-view-item-slug': 'code-block' }),
    );
    harness.contentHeader.dispatch('click', target({ 'data-back-from-item': '' }));

    expect(harness.contentHeader.innerHTML).toContain('<h1>Registries</h1>');
  });

  it('uses push history for navigation but not search typing', () => {
    const harness = setup('?view=discover');
    const initialPushes = harness.history.pushes.length;

    harness.tabs[1].dispatch('click', {});
    expect(harness.history.pushes.length).toBe(initialPushes + 1);

    const pushesAfterNavigation = harness.history.pushes.length;
    harness.searchInput.value = 'button';
    harness.searchInput.dispatch('input', {});
    expect(harness.history.pushes.length).toBe(pushesAfterNavigation);
  });

  it('opens peek explicitly, dismisses it with Escape, and restores trigger focus', () => {
    const harness = setup('?view=discover&registry=%40delta');
    const trigger = target({
      class: 'component-peek-trigger',
      'data-component-peek-id': '@delta:code-block',
      'data-view-item-registry': '@delta',
      'data-view-item-slug': 'code-block',
    });
    harness.contentBody.querySelectorAll = () => [trigger];

    harness.contentBody.dispatch('click', trigger);
    expect(harness.contentBody.innerHTML).toContain('data-component-peek-popover');
    expect(trigger.getAttribute('aria-expanded')).toBe('true');
    expect(trigger.getAttribute('aria-haspopup')).toBeNull();
    expect(harness.contentHeader.innerHTML).toContain('@delta');

    harness.contentBody.dispatch('keydown', trigger, { key: 'Escape' });

    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-popover');
    expect(trigger.getAttribute('aria-expanded')).toBe('false');
    expect(trigger.focus).toHaveBeenCalled();
  });

  it('clears a hover peek when the pointer leaves the trigger', () => {
    const harness = setup('?view=discover&registry=%40delta');
    const trigger = target({
      class: 'component-peek-trigger',
      'data-component-peek-id': '@delta:code-block',
      'data-view-item-registry': '@delta',
      'data-view-item-slug': 'code-block',
    });
    harness.contentBody.querySelectorAll = () => [trigger];

    harness.contentBody.dispatch('mouseover', trigger);
    expect(harness.contentBody.innerHTML).toContain('data-component-peek-popover');

    harness.contentBody.dispatch(
      'mouseout',
      target({ 'data-component-peek-popover': '@delta:code-block' }),
      { relatedTarget: target({}) },
    );

    expect(harness.contentBody.innerHTML).not.toContain('data-component-peek-popover');
  });
});

function setup(search: string) {
  const location = {
    pathname: '/Registry-Atlas/',
    search,
    hash: '',
    href: `http://localhost/Registry-Atlas/${search}`,
  };
  const windowListeners = new Map<string, ((event: any) => void)[]>();
  const history = {
    pushes: [] as string[],
    replaces: [] as string[],
    pushState(_state: unknown, _title: string, next: string) {
      this.pushes.push(next);
      updateLocation(next);
    },
    replaceState(_state: unknown, _title: string, next: string) {
      this.replaces.push(next);
      updateLocation(next);
    },
  };
  function updateLocation(next: string): void {
    const url = new URL(next, 'http://localhost');
    location.pathname = url.pathname;
    location.search = url.search;
    location.hash = url.hash;
    location.href = url.href;
  }
  vi.stubGlobal('window', {
    location,
    history,
    addEventListener(type: string, listener: (event: any) => void) {
      const listeners = windowListeners.get(type) ?? [];
      listeners.push(listener);
      windowListeners.set(type, listeners);
    },
  });

  const aside = root();
  const contentHeader = root();
  const contentBody = root();
  const tabs = [tab('discover'), tab('registries'), tab('compare')];
  const searchInput = input();
  initRegistryExplorer({
    registries: [registryFixture()],
    mirrorMeta: {
      source_url: 'https://atlas.example/source',
      synced_at: '2026-08-25T00:00:00.000Z',
      upstream_count: 1,
      registry_count: 1,
      local_count: 1,
      validation_status: 'valid',
      report_path: 'report.json',
    },
    mirrorWarnings: [],
    roots: {
      aside: aside as unknown as HTMLElement,
      contentHeader: contentHeader as unknown as HTMLElement,
      contentBody: contentBody as unknown as HTMLElement,
      tabs: tabs as unknown as NodeListOf<Element>,
      searchInput: searchInput as unknown as HTMLInputElement,
    },
  });

  return { aside, contentHeader, contentBody, tabs, searchInput, location, history, windowListeners };
}

function root(): FakeRoot {
  return {
    innerHTML: '',
    listeners: new Map(),
    addEventListener(type, listener) {
      const listeners = this.listeners.get(type) ?? [];
      listeners.push(listener);
      this.listeners.set(type, listeners);
    },
    insertAdjacentHTML(_position, html) {
      this.innerHTML += html;
    },
    dispatch(type, target, extra = {}) {
      this.listeners.get(type)?.forEach(listener => listener({ target, preventDefault: vi.fn(), ...extra }));
    },
    querySelectorAll: () => [],
  };
}

function tab(view: string) {
  const item = root() as FakeRoot & { getAttribute: (name: string) => string | null; classList: { toggle: () => void } };
  item.getAttribute = name => name === 'data-view' ? view : null;
  item.classList = { toggle: vi.fn() };
  return item;
}

function input() {
  const item = root() as FakeRoot & { value: string };
  item.value = '';
  return item;
}

function target(attributes: Record<string, string>) {
  const focus = vi.fn();
  return {
    focus,
    classList: {
      contains: (name: string) => (attributes.class ?? '').split(' ').includes(name),
    },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: (selector: string) => {
      if (selector.includes('.component-peek-trigger') && !attributes.class?.split(' ').includes('component-peek-trigger')) return null;
      const names = [...selector.matchAll(/\[([a-zA-Z0-9_-]+)/g)].map(match => match[1]);
      return names.some(name => name in attributes) ? targetWithFocus(attributes, focus) : null;
    },
  };
}

function targetWithFocus(attributes: Record<string, string>, focus: ReturnType<typeof vi.fn>) {
  return {
    focus,
    classList: { contains: (name: string) => (attributes.class ?? '').split(' ').includes(name) },
    getAttribute: (name: string) => attributes[name] ?? null,
    setAttribute: (name: string, value: string) => { attributes[name] = value; },
    hasAttribute: (name: string) => name in attributes,
    closest: () => null,
  };
}

function registryFixture(): Registry {
  return {
    name: '@delta',
    url: 'https://delta.example',
    description: 'Delta registry fixture.',
    primary_focus: ['support'],
    component_tags: ['code-block'],
    atlas: {
      aliases: [],
      coverageStatus: 'verified',
      confidence: 'high',
      notes: 'Fixture notes.',
      catalogStatus: 'available',
    },
    itemSummaries: [{
      name: 'Code Block',
      slug: 'code-block',
      title: 'Code Block',
      description: 'Syntax highlighted code block.',
      type: 'registry:ui',
      category: 'code',
      componentTagsProposed: ['code-block'],
      source: 'registry-json',
      provenance: 'fixture',
      catalogStatus: 'available',
      confidence: 'high',
      routeEligible: true,
      rawItemUrl: 'https://delta.example/r/code-block.json',
      docsUrl: 'https://delta.example/components/code-block',
      installCommand: 'npx shadcn add @delta/code-block',
      viewCommand: 'npx shadcn view @delta/code-block',
      dependencies: [],
      registryDependencies: [],
      files: [],
    }],
  };
}
